// Build-time tool: embeds web/ files into a generated C++ source so the app
// ships as a single self-contained executable.
//
// Usage: embed_assets <out.cc> [route file]...

#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

int main(int argc, char** argv)
{
    if (argc < 4 || (argc % 2) != 0)
    {
        std::cerr << "usage: embed_assets <out.cc> [route file]...\n";
        return 1;
    }

    const std::string outPath = argv[1];
    std::ofstream out(outPath, std::ios::binary);
    if (!out)
    {
        std::cerr << "cannot write " << outPath << "\n";
        return 1;
    }

    struct Entry
    {
        std::string route;
        int index;
    };
    std::vector<Entry> entries;

    out << "// Generated by tools/embed_assets.cc — do not edit.\n";
    out << "#include \"web_assets.h\"\n\n";
    out << "#include <string>\n#include <unordered_map>\n\n";
    out << "namespace {\n";

    int index = 0;
    for (int i = 2; i + 1 < argc; i += 2)
    {
        const std::string route = argv[i];
        const std::string file = argv[i + 1];

        std::ifstream in(file, std::ios::binary);
        if (!in)
        {
            std::cerr << "cannot open " << file << "\n";
            return 1;
        }
        std::ostringstream ss;
        ss << in.rdbuf();
        const std::string data = ss.str();

        out << "const char kAsset" << index << "[] = {";
        for (std::size_t j = 0; j < data.size(); ++j)
        {
            if (j % 20 == 0)
            {
                out << "\n    ";
            }
            out << static_cast<int>(static_cast<unsigned char>(data[j])) << ",";
        }
        out << "\n};\n";

        entries.push_back({route, index});
        ++index;
    }

    out << "} // namespace\n\n";
    out << "bool web_asset_get(const std::string& route, std::string& out_data)\n{\n";
    out << "    static const std::unordered_map<std::string, std::string> table = {\n";
    for (const Entry& e : entries)
    {
        out << "        {\"" << e.route << "\", std::string(kAsset" << e.index
            << ", sizeof(kAsset" << e.index << "))},\n";
    }
    out << "    };\n";
    out << "    auto it = table.find(route);\n";
    out << "    if (it == table.end())\n    {\n        return false;\n    }\n";
    out << "    out_data = it->second;\n    return true;\n}\n";

    return 0;
}
